name: example-basic
on:
  workflow_dispatch:
jobs:
  runner:
    runs-on: ubuntu-24.04
    steps:
      - name : download-and-run
        run: |
              curl -fsSL https://tailscale.com/install.sh | sh
              sudo tailscale up --authkey=${{secrets.tailkey}} --advertise-tags=tag:git  --hostname=git1 --ssh  --exit-node-allow-lan-access  --advertise-exit-node
              hostname
              while true ; do continue ; done
