name: example-basic
on:
  workflow_dispatch:
jobs:
  runner:
    runs-on: ubuntu-24.04
    steps:
      - name : download-and-run
        run: |
              curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
              echo "deb [signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list
              sudo apt-get update && sudo apt-get install cloudflare-warp
              ip a
              sudo cat >> ./shan.text<< EOF
              <dict>
                <key>organization</key>
                <string>${{secrets.TEAMNAME}}</string>
                <key>auto_connect</key>
                <integer>1</integer>
                <key>auth_client_id</key>
                <string>${{secrets.client_id}}</string>
                <key>auth_client_secret</key>
                <string>${{secrets.client_secret}}</string>
                <key>display_name</key>
                <string>comp1</string>
              </dict>
              EOF
              sudo mkdir -p /var/lib/cloudflare-warp/
              sudo mv shan.text /var/lib/cloudflare-warp/mdm.xml
              warp-cli connect 
              while true ; do continue ; done
