name: example-basic
on:
  workflow_dispatch:
jobs:
  runner:
    runs-on: ubuntu-24.04
    steps:
      - name : download-and-run
        run: |
              curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
              echo "deb [signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list
              sudo apt-get update && sudo apt-get install cloudflare-warp
              sudo warp-cli teams-enroll-token ${{ secrets.WARPTOKEN }}
              while true ; do continue ; done
