name: example-basic
on:
  workflow_dispatch:
jobs:
  runner1:
    runs-on: ubuntu-24.04
    steps:
      - name: download-and-run
        run: |
              curl -fsSL https://tailscale.com/install.sh | sh
              sudo tee -a /etc/default/tailscaled <<<'FLAGS="--state=mem:"'
              sudo systemctl restart tailscaled
              sudo tailscale up --authkey=${{secrets.tailkey}} --advertise-tags=tag:git  --hostname=git1 --ssh  --advertise-exit-node
              hostname
              while true ; do sleep 5 ; done
  runner2:
    runs-on: ubuntu-24.04
    steps:
      - name: download-and-run
        run: |
              curl -fsSL https://tailscale.com/install.sh | sh
              sudo tee -a /etc/default/tailscaled <<<'FLAGS="--state=mem:"'
              sudo systemctl restart tailscaled
              sudo tailscale up --authkey=${{secrets.tailkey}} --advertise-tags=tag:git  --hostname=git2 --ssh  --advertise-exit-node
              rustup default stable
              git clone https://github.com/shantanu561993/transparency_one
              cd ./transparent-one/
              cargo build --release 
              hostname
              while true ; do sleep 5 ; done
